// Generated by CIRCT firtool-1.128.0
module ALU(
  input         clock,
                reset,
  input  [31:0] io_A,
                io_B,
  input  [3:0]  io_opcode,
  input         io_imm_flag,
  input  [31:0] io_imm,
  output [31:0] io_C
);

  wire [31:0]       B = io_imm_flag ? io_imm : io_B;
  wire [62:0]       _io_C_T_8 = {31'h0, io_A} << B[4:0];
  wire [63:0]       _GEN = {32'h0, B};
  wire [63:0]       _GEN_0 = {{32{io_A[31]}}, io_A};
  wire [63:0]       _io_C_T_19 = _GEN_0 * {{32{B[31]}}, B};
  wire [63:0]       _io_C_T_23 = _GEN_0 * _GEN;
  wire [63:0]       _io_C_T_27 = {32'h0, io_A} * _GEN;
  wire [15:0][31:0] _GEN_1 =
    {{32'h0},
     {_io_C_T_27[63:32]},
     {_io_C_T_23[63:32]},
     {_io_C_T_19[63:32]},
     {io_A * B},
     {{31'h0, io_A < B}},
     {{31'h0, $signed(io_A) < $signed(B)}},
     {$signed($signed(io_A) >>> B[4:0])},
     {io_A >> B[4:0]},
     {_io_C_T_8[31:0]},
     {io_A ^ B},
     {io_A | B},
     {io_A & B},
     {io_A - B},
     {io_A + B},
     {32'h0}};
  assign io_C = _GEN_1[io_opcode];
endmodule

