// Generated by CIRCT firtool-1.128.0
module RegisterFile(
  input         clock,
                reset,
  input  [3:0]  io_opcode,
  input  [31:0] io_C,
  input  [4:0]  io_readAddressA,
                io_readAddressB,
  input         io_writeEnable,
  input  [4:0]  io_writeAddress,
  output [31:0] io_A,
                io_B
);

  reg  [31:0]       regFile_0;
  reg  [31:0]       regFile_1;
  reg  [31:0]       regFile_2;
  reg  [31:0]       regFile_3;
  reg  [31:0]       regFile_4;
  reg  [31:0]       regFile_5;
  reg  [31:0]       regFile_6;
  reg  [31:0]       regFile_7;
  reg  [31:0]       regFile_8;
  reg  [31:0]       regFile_9;
  reg  [31:0]       regFile_10;
  reg  [31:0]       regFile_11;
  reg  [31:0]       regFile_12;
  reg  [31:0]       regFile_13;
  reg  [31:0]       regFile_14;
  reg  [31:0]       regFile_15;
  reg  [31:0]       regFile_16;
  reg  [31:0]       regFile_17;
  reg  [31:0]       regFile_18;
  reg  [31:0]       regFile_19;
  reg  [31:0]       regFile_20;
  reg  [31:0]       regFile_21;
  reg  [31:0]       regFile_22;
  reg  [31:0]       regFile_23;
  reg  [31:0]       regFile_24;
  reg  [31:0]       regFile_25;
  reg  [31:0]       regFile_26;
  reg  [31:0]       regFile_27;
  reg  [31:0]       regFile_28;
  reg  [31:0]       regFile_29;
  reg  [31:0]       regFile_30;
  reg  [31:0]       regFile_31;
  wire [31:0][31:0] _GEN =
    {{regFile_31},
     {regFile_30},
     {regFile_29},
     {regFile_28},
     {regFile_27},
     {regFile_26},
     {regFile_25},
     {regFile_24},
     {regFile_23},
     {regFile_22},
     {regFile_21},
     {regFile_20},
     {regFile_19},
     {regFile_18},
     {regFile_17},
     {regFile_16},
     {regFile_15},
     {regFile_14},
     {regFile_13},
     {regFile_12},
     {regFile_11},
     {regFile_10},
     {regFile_9},
     {regFile_8},
     {regFile_7},
     {regFile_6},
     {regFile_5},
     {regFile_4},
     {regFile_3},
     {regFile_2},
     {regFile_1},
     {regFile_0}};
  always @(posedge clock) begin
    if (reset) begin
      regFile_0 <= 32'h0;
      regFile_1 <= 32'h0;
      regFile_2 <= 32'h0;
      regFile_3 <= 32'h0;
      regFile_4 <= 32'h0;
      regFile_5 <= 32'h0;
      regFile_6 <= 32'h0;
      regFile_7 <= 32'h0;
      regFile_8 <= 32'h0;
      regFile_9 <= 32'h0;
      regFile_10 <= 32'h0;
      regFile_11 <= 32'h0;
      regFile_12 <= 32'h0;
      regFile_13 <= 32'h0;
      regFile_14 <= 32'h0;
      regFile_15 <= 32'h0;
      regFile_16 <= 32'h0;
      regFile_17 <= 32'h0;
      regFile_18 <= 32'h0;
      regFile_19 <= 32'h0;
      regFile_20 <= 32'h0;
      regFile_21 <= 32'h0;
      regFile_22 <= 32'h0;
      regFile_23 <= 32'h0;
      regFile_24 <= 32'h0;
      regFile_25 <= 32'h0;
      regFile_26 <= 32'h0;
      regFile_27 <= 32'h0;
      regFile_28 <= 32'h0;
      regFile_29 <= 32'h0;
      regFile_30 <= 32'h0;
      regFile_31 <= 32'h0;
    end
    else begin
      automatic logic _GEN_0 = io_writeEnable & (|io_writeAddress);
      if (_GEN_0 & ~(|io_writeAddress))
        regFile_0 <= io_C;
      if (_GEN_0 & io_writeAddress == 5'h1)
        regFile_1 <= io_C;
      if (_GEN_0 & io_writeAddress == 5'h2)
        regFile_2 <= io_C;
      if (_GEN_0 & io_writeAddress == 5'h3)
        regFile_3 <= io_C;
      if (_GEN_0 & io_writeAddress == 5'h4)
        regFile_4 <= io_C;
      if (_GEN_0 & io_writeAddress == 5'h5)
        regFile_5 <= io_C;
      if (_GEN_0 & io_writeAddress == 5'h6)
        regFile_6 <= io_C;
      if (_GEN_0 & io_writeAddress == 5'h7)
        regFile_7 <= io_C;
      if (_GEN_0 & io_writeAddress == 5'h8)
        regFile_8 <= io_C;
      if (_GEN_0 & io_writeAddress == 5'h9)
        regFile_9 <= io_C;
      if (_GEN_0 & io_writeAddress == 5'hA)
        regFile_10 <= io_C;
      if (_GEN_0 & io_writeAddress == 5'hB)
        regFile_11 <= io_C;
      if (_GEN_0 & io_writeAddress == 5'hC)
        regFile_12 <= io_C;
      if (_GEN_0 & io_writeAddress == 5'hD)
        regFile_13 <= io_C;
      if (_GEN_0 & io_writeAddress == 5'hE)
        regFile_14 <= io_C;
      if (_GEN_0 & io_writeAddress == 5'hF)
        regFile_15 <= io_C;
      if (_GEN_0 & io_writeAddress == 5'h10)
        regFile_16 <= io_C;
      if (_GEN_0 & io_writeAddress == 5'h11)
        regFile_17 <= io_C;
      if (_GEN_0 & io_writeAddress == 5'h12)
        regFile_18 <= io_C;
      if (_GEN_0 & io_writeAddress == 5'h13)
        regFile_19 <= io_C;
      if (_GEN_0 & io_writeAddress == 5'h14)
        regFile_20 <= io_C;
      if (_GEN_0 & io_writeAddress == 5'h15)
        regFile_21 <= io_C;
      if (_GEN_0 & io_writeAddress == 5'h16)
        regFile_22 <= io_C;
      if (_GEN_0 & io_writeAddress == 5'h17)
        regFile_23 <= io_C;
      if (_GEN_0 & io_writeAddress == 5'h18)
        regFile_24 <= io_C;
      if (_GEN_0 & io_writeAddress == 5'h19)
        regFile_25 <= io_C;
      if (_GEN_0 & io_writeAddress == 5'h1A)
        regFile_26 <= io_C;
      if (_GEN_0 & io_writeAddress == 5'h1B)
        regFile_27 <= io_C;
      if (_GEN_0 & io_writeAddress == 5'h1C)
        regFile_28 <= io_C;
      if (_GEN_0 & io_writeAddress == 5'h1D)
        regFile_29 <= io_C;
      if (_GEN_0 & io_writeAddress == 5'h1E)
        regFile_30 <= io_C;
      if (_GEN_0 & (&io_writeAddress))
        regFile_31 <= io_C;
    end
  end // always @(posedge)
  assign io_A = io_readAddressA == 5'h0 ? 32'h0 : _GEN[io_readAddressA];
  assign io_B = io_readAddressB == 5'h0 ? 32'h0 : _GEN[io_readAddressB];
endmodule

